[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Base network configuration
[rpc_endpoints]
base = "https://mainnet.base.org"
base-sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base-sepolia = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
